In [1]:
import pandas as pd

### `Q-1`: Write a program to create an empty series

In [3]:
pd.Series()

Series([], dtype: object)

### `Q-2:` Write a Pandas program to add, subtract, multiple and divide two Pandas Series.

In [4]:
a= pd.Series([2, 4, 6, 8, 10])
b= pd.Series([1, 3, 5, 7, 10])

In [8]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

0     3
1     7
2    11
3    15
4    20
dtype: int64
0    1
1    1
2    1
3    1
4    0
dtype: int64
0      2
1     12
2     30
3     56
4    100
dtype: int64
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.000000
dtype: float64

### `Q-3` Write a Pandas program to compare the elements of the two Pandas Series.
Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 10]

In [9]:
a = pd.Series([2, 4, 6, 8, 10])
b = pd.Series([1, 3, 5, 7, 10])

print(a==b)
print(a<b)
print(a>b)

0    False
1    False
2    False
3    False
4     True
dtype: bool
0    False
1    False
2    False
3    False
4    False
dtype: bool
0     True
1     True
2     True
3     True
4    False
dtype: bool

### `Q-5.`Write a function to change the data type of given a column or a Series. Function takes series and data type as input, returns the converted series.
```
series = pd.Series([1,2,'Python', 2.0, True, 100])
change to float type data
```
Note: Read about pd.to_numeric()

In [21]:
series = pd.Series([1,2,'Python', 2.0, True, 100])

In [22]:
def change_dtype(series):
  return pd.to_numeric(series, errors='coerce')

In [23]:
change_dtype(series)

0      1.0
1      2.0
2      NaN
3      2.0
4      1.0
5    100.0
dtype: float64

In [24]:
data = pd.read_csv("/content/drive/MyDrive/Python-for-Data-Science/05_Pandas/dataset/batsman_runs_series.csv")

In [26]:
data.head()

           batter  batsman_run
0  A Ashish Reddy          280
1        A Badoni          161
2      A Chandila            4
3        A Chopra           53
4     A Choudhary           25

In [31]:
data.tail()

            batter  batsman_run
600     Yash Dayal            0
601  Yashpal Singh           47
602    Younis Khan            3
603   Yuvraj Singh         2754
604         Z Khan          117

### `Q-6` Find top 10 most run getter from the series.

In [35]:
data.sort_values('batsman_run', ascending=False).head(10)

             batter  batsman_run
569         V Kohli         6634
462        S Dhawan         6244
130       DA Warner         5883
430       RG Sharma         5881
493        SK Raina         5536
27   AB de Villiers         5181
108        CH Gayle         4997
339        MS Dhoni         4978
452      RV Uthappa         4954
256      KD Karthik         4377

### `Q-7` No of players having runs above 3000

In [40]:
data[data['batsman_run']>3000].shape[0]

20

### `Q-8` No of players having runs above mean value?

In [44]:
data[data['batsman_run'] > data['batsman_run'].mean()].shape[0]

128

### `Q-9`
    i. Read `items.csv` making `item_name` as index.
    ii. Show no of nan values
    ii. Item price is given in $, so convert it to rupees without currency symbol.
    iii. Make data type of newly made series as float.
    iv. Fill nan with mean of the series

In [58]:
#1
item = pd.read_csv("/content/drive/MyDrive/Python-for-Data-Science/05_Pandas/dataset/items.csv", index_col='item_name')

In [59]:
item = item.squeeze()
item

item_name
Chips and Fresh Tomato Salsa              $2.39
Izze                                      $3.39
Nantucket Nectar                          $3.39
Chips and Tomatillo-Green Chili Salsa     $2.39
Chicken Bowl                             $16.98
                                          ...
Steak Burrito                            $11.75
Steak Burrito                            $11.75
Chicken Salad Bowl                       $11.25
Chicken Salad Bowl                        $8.75
Chicken Salad Bowl                        $8.75
Name: item_price, Length: 4622, dtype: object

In [53]:
item.tail()

item_name
Steak Burrito         $11.75
Steak Burrito         $11.75
Chicken Salad Bowl    $11.25
Chicken Salad Bowl     $8.75
Chicken Salad Bowl     $8.75
Name: item_price, dtype: object

In [60]:
# ii. Show no of nan values
item.isna().sum()

np.int64(50)

In [61]:
!git clone https://github.com

Cloning into 'github.com'...
fatal: repository 'https://github.com/' not found