In [2]:
import numpy as np
import pandas as pd

In [ ]:
# to visualize all the column, run the below code
# pd.options.display.max_columns = None
# to show all the records, use the below code
pd.options.display.max_rows = None

## Fifa Worldcup - 2022 dataset.

Dataset link: [here](https://www.kaggle.com/datasets/sayanroy729/fifa-worldcup-2022-results).

Also you can directly use an url to read the dataset by using `pd.read_csv()` method. Check the below code cell.

In [3]:
url = "https://docs.google.com/spreadsheets/d/e/2PACX-1vT3D_x_4DS6d51LKJ7ze1sxT5WpV5uiSVOFYHLwBiGru6vFyVv5h5-83AwFjxWYiWfCDjDAaarHAV-k/pub?gid=0&single=true&output=csv"
df = pd.read_csv(url)
df.head()

,Sl. No,Match No.,Team,Against,Group,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,...,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored,Pts
0,1,1,Qatar,Ecuador,A,0,40,0,0,0,...,15,3,453,387,10,5,1,19,0,0
1,2,1,Ecuador,Qatar,A,2,46,2,0,1,...,15,4,484,419,26,10,3,17,1,3
2,3,2,England,Iran,B,6,69,6,0,6,...,9,2,810,733,29,9,8,16,0,3
3,4,2,Iran,England,B,2,20,2,0,1,...,14,2,232,156,11,3,0,10,1,0
4,5,3,Senegal,Netherlands,A,0,39,0,0,0,...,13,2,391,326,22,8,6,14,0,0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128 entries, 0 to 127
Data columns (total 38 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Sl. No                           128 non-null    int64
 1   Match No.                        128 non-null    int64
 2   Team                             128 non-null    object
 3   Against                          128 non-null    object
 4   Group                            128 non-null    object
 5   Goal                             128 non-null    int64
 6   Possession (%)                   128 non-null    int64
 7   Inside Penalty Area              128 non-null    int64
 8   Outside Penalty Area             128 non-null    int64
 9   Assists                          128 non-null    int64
 10  Total Attempts                   128 non-null    int64
 11  On Target                        128 non-null    int64
 12  Off Target                       128 non-null    int64
 13  Target in Penalty                128 non-null    int64
 14  Target from Outside              128 non-null    int64
 15  Left Channel                     128 non-null    int64
 16  Left Inside Channel              128 non-null    int64
 17  Central Channel                  128 non-null    int64
 18  Right Inside Channel             128 non-null    int64
 19  Right Channel                    128 non-null    int64
 20  Receptions MD                    128 non-null    int64
 21  Receptions D                     128 non-null    int64
 22  Attempted Line Breaks            128 non-null    int64
 23  Completed Line Breaks            128 non-null    int64
 24  Attempted Defensive Line Breaks  128 non-null    int64
 25  Completed Defensive Line Breaks  128 non-null    int64
 26  Yellow Cards                     128 non-null    int64
 27  Red Cards                        128 non-null    int64
 28  Fouls Against                    128 non-null    int64
 29  Offsides                         128 non-null    int64
 30  Passes                           128 non-null    int64
 31  Passes Completed                 128 non-null    int64
 32  Crosses                          128 non-null    int64
 33  Crosses Completed                128 non-null    int64
 34  Corners                          128 non-null    int64
 35  Free Kicks                       128 non-null    int64
 36  Penalties Scored                 128 non-null    int64
 37  Pts                              128 non-null    int64
dtypes: int64(35), object(3)
memory usage: 38.1+ KB

### `Q-1:` Use the football dataset. Find out the total percentages that each team made on target. Display the result as a python dictionary where the keys are the team list and the values are the percentage values. Round off the percentage values up to 2 decimal places.

*Help:*
- First, find out how many total teams are participated in this worldcup. For that, you can use `unique()` method on the column "Team" or "Against".
- Loop through the teams list that you have found in previous section, and then filter the dataset according to that. After filtering the dataset, find out total attempts sum and total on target sum.
- After getting these values, find out the percentage by total on target divided by total attempts and multiply by 100. And store to a python dictionary where the key will be the team name and the values will be the percentages.
- At the end,sort the dictionary by the values (not by the keys) and print the result.


**Sample Output:**
```bash
{'Costa Rica': 54.55,
 'Cameroon': 51.85,
 'Ecuador': 48.15,
 'Argentina': 46.99,
 'Brazil': 45.56,
 'England': 45.0,
 'Portugal': 40.32,
 'Ghana': 40.0,
 'Netherlands': 39.02,
 'Korea Republic': 36.73,
 'Australia': 36.0,
 'Mexico': 34.88,
 'Croatia': 34.78,
 'Germany': 34.33,
 'France': 32.97,
 'Spain': 32.69,
 'Belgium': 32.35,
 'Serbia': 32.26,
 'Iran': 31.43,
 'Uruguay': 31.25,
 'United States': 31.11,
 'Saudi Arabia': 31.03,
 'Senegal': 30.77,
 'Denmark': 30.56,
 'Switzerland': 30.56,
 'Japan': 30.23,
 'Wales': 29.17,
 'Qatar': 28.57,
 'Morocco': 28.3,
 'Tunisia': 26.67,
 'Poland': 25.0,
 'Canada': 17.65}
```

In [ ]:
all_teams = df.Team.unique()
on_target_percentge = {}
for team in all_teams:
    total_attempts = df[df['Team'] == team ]["Total Attempts"].sum()
    total_on_target = df[df['Team'] == team]["On Target"].sum()
    on_target_percentge[team] = round(total_on_target / total_attempts * 100,2)
dict(sorted(on_target_percentge.items(), key = lambda x:x[1], reverse = True))
# on_target_percentge
#

{'Costa Rica': np.float64(54.55),
 'Cameroon': np.float64(51.85),
 'Ecuador': np.float64(48.15),
 'Argentina': np.float64(46.15),
 'Brazil': np.float64(45.56),
 'England': np.float64(45.0),
 'Portugal': np.float64(40.32),
 'Ghana': np.float64(40.0),
 'Netherlands': np.float64(39.02),
 'Korea Republic': np.float64(36.73),
 'Australia': np.float64(36.0),
 'Mexico': np.float64(34.88),
 'France': np.float64(34.65),
 'Germany': np.float64(34.33),
 'Croatia': np.float64(33.73),
 'Spain': np.float64(32.69),
 'Belgium': np.float64(32.35),
 'Serbia': np.float64(32.26),
 'Iran': np.float64(31.43),
 'Uruguay': np.float64(31.25),
 'United States': np.float64(31.11),
 'Saudi Arabia': np.float64(31.03),
 'Senegal': np.float64(30.77),
 'Denmark': np.float64(30.56),
 'Switzerland': np.float64(30.56),
 'Japan': np.float64(30.23),
 'Wales': np.float64(29.17),
 'Qatar': np.float64(28.57),
 'Morocco': np.float64(28.33),
 'Tunisia': np.float64(26.67),
 'Poland': np.float64(25.0),
 'Canada': np.float64(17.65)}

### `Q-2:` Find out how many times the teams are played in this Fifa Worldcup-2022. On top of this, find out the ranks of the teams.

Note: The `DataFrame.rank()` method takes an optiinal parameter named `method`. This parameter takes different values, but one of them is `average` which is by-default. So, when you do the rank, you will get some 2.5 like floating values. But if you change the value as `first`, then you will get in integers but the datatype will be float. So, try with `method="first"` parameter.

In [ ]:
df['Team'].value_counts().rank(method='first')
#

Team
France            29.0
Argentina         30.0
Croatia           31.0
Morocco           32.0
Brazil            25.0
Portugal          26.0
England           27.0
Netherlands       28.0
Spain             17.0
Japan             18.0
Switzerland       19.0
Korea Republic    20.0
Australia         21.0
Poland            22.0
Senegal           23.0
United States     24.0
Mexico             1.0
Saudi Arabia       2.0
Denmark            3.0
Tunisia            4.0
Iran               5.0
Ecuador            6.0
Qatar              7.0
Wales              8.0
Canada             9.0
Belgium           10.0
Costa Rica        11.0
Germany           12.0
Uruguay           13.0
Cameroon          14.0
Ghana             15.0
Serbia            16.0
Name: count, dtype: float64

In [19]:
print(df.info())
print(df.describe())
print(df.isna().sum())
df.drop_duplicates(inplace=True)
df.drop(columns=['Sl. No', 'Match No.', 'Red Cards', 'Pts'], inplace=True)
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128 entries, 0 to 127
Data columns (total 35 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Team                             128 non-null    object
 1   Against                          128 non-null    object
 2   Group                            128 non-null    object
 3   Goal                             128 non-null    int64
 4   Possession (%)                   128 non-null    int64
 5   Inside Penalty Area              128 non-null    int64
 6   Outside Penalty Area             128 non-null    int64
 7   Assists                          128 non-null    int64
 8   Total Attempts                   128 non-null    int64
 9   On Target                        128 non-null    int64
 10  Off Target                       128 non-null    int64
 11  Target in Penalty                128 non-null    int64
 12  Target from Outside              128 non-null    int64
 13  Left Channel                     128 non-null    int64
 14  Left Inside Channel              128 non-null    int64
 15  Central Channel                  128 non-null    int64
 16  Right Inside Channel             128 non-null    int64
 17  Right Channel                    128 non-null    int64
 18  Receptions MD                    128 non-null    int64
 19  Receptions D                     128 non-null    int64
 20  Attempted Line Breaks            128 non-null    int64
 21  Completed Line Breaks            128 non-null    int64
 22  Attempted Defensive Line Breaks  128 non-null    int64
 23  Completed Defensive Line Breaks  128 non-null    int64
 24  Yellow Cards                     128 non-null    int64
 25  Fouls Against                    128 non-null    int64
 26  Offsides                         128 non-null    int64
 27  Passes                           128 non-null    int64
 28  Passes Completed                 128 non-null    int64
 29  Crosses                          128 non-null    int64
 30  Crosses Completed                128 non-null    int64
 31  Corners                          128 non-null    int64
 32  Free Kicks                       128 non-null    int64
 33  Penalties Scored                 128 non-null    int64
 34  Rank                             128 non-null    float64
dtypes: float64(1), int64(31), object(3)
memory usage: 35.1+ KB
None
             Goal  Possession (%)  Inside Penalty Area  Outside Penalty Area  \
count  128.000000      128.000000           128.000000            128.000000
mean     1.343750       43.476562             1.203125              0.117188
std      1.342448       11.442403             1.324270              0.322907
min      0.000000       14.000000             0.000000              0.000000
25%      0.000000       35.000000             0.000000              0.000000
50%      1.000000       45.000000             1.000000              0.000000
75%      2.000000       51.000000             2.000000              0.000000
max      7.000000       78.000000             7.000000              1.000000

          Assists  Total Attempts   On Target  Off Target  Target in Penalty  \
count  128.000000      128.000000  128.000000  128.000000         128.000000
mean     0.914062       11.257812    4.007812    4.835938           6.914062
std      1.150333        5.406683    2.588576    2.610630           3.998085
min      0.000000        0.000000    0.000000    0.000000           0.000000
25%      0.000000        7.750000    2.000000    3.000000           4.000000
50%      1.000000       10.000000    4.000000    4.000000           6.000000
75%      1.000000       14.000000    6.000000    6.000000           9.000000
max      6.000000       32.000000   13.000000   17.000000          24.000000

       Target from Outside  ...  Fouls Against    Offsides       Passes  \
count           128.000000  ...     128.000000  128.000000   128.000000
mean              4.343750  ...      12.320312    1.976562   502.859375
std               2.733397  ...       4.691983    1.731891   160.160487
min               0.000000  ...       0.000000    0.000000   225.000000
25%               3.000000  ...       9.000000    1.000000   398.250000
50%               4.000000  ...      12.000000    2.000000   495.500000
75%               5.000000  ...      15.000000    3.000000   589.500000
max              15.000000  ...      30.000000   10.000000  1070.000000

       Passes Completed     Crosses  Crosses Completed     Corners  \
count        128.000000  128.000000         128.000000  128.000000
mean         430.929688   19.523438           4.898438    4.468750
std          160.893724    8.596799           3.520111    2.774852
min          156.000000    4.000000           0.000000    0.000000
25%          323.250000   13.000000           3.000000    2.000000
50%          419.000000   19.000000           4.000000    4.000000
75%          519.750000   24.000000           6.000000    6.000000
max          994.000000   53.000000          25.000000   14.000000

       Free Kicks  Penalties Scored        Rank
count  128.000000        128.000000  128.000000
mean    14.250000          0.335938   64.500000
std      4.712189          0.941412   37.094474
min      5.000000          0.000000    1.000000
25%     11.000000          0.000000   32.750000
50%     14.000000          0.000000   64.500000
75%     17.000000          0.000000   96.250000
max     30.000000          5.000000  128.000000

[8 rows x 32 columns]
Team                               0
Against                            0
Group                              0
Goal                               0
Possession (%)                     0
Inside Penalty Area                0
Outside Penalty Area               0
Assists                            0
Total Attempts                     0
On Target                          0
Off Target                         0
Target in Penalty                  0
Target from Outside                0
Left Channel                       0
Left Inside Channel                0
Central Channel                    0
Right Inside Channel               0
Right Channel                      0
Receptions MD                      0
Receptions D                       0
Attempted Line Breaks              0
Completed Line Breaks              0
Attempted Defensive Line Breaks    0
Completed Defensive Line Breaks    0
Yellow Cards                       0
Fouls Against                      0
Offsides                           0
Passes                             0
Passes Completed                   0
Crosses                            0
Crosses Completed                  0
Corners                            0
Free Kicks                         0
Penalties Scored                   0
Rank                               0
dtype: int64

,Team,Against,Group,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,Total Attempts,On Target,...,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored,Rank
0,Qatar,Ecuador,A,0,40,0,0,0,5,0,...,15,3,453,387,10,5,1,19,0,95.0
1,Ecuador,Qatar,A,2,46,2,0,1,5,5,...,15,4,484,419,26,10,3,17,1,39.0
2,England,Iran,B,6,69,6,0,6,13,7,...,9,2,810,733,29,9,8,16,0,42.0
3,Iran,England,B,2,20,2,0,1,8,3,...,14,2,232,156,11,3,0,10,1,60.0
4,Senegal,Netherlands,A,0,39,0,0,0,15,4,...,13,2,391,326,22,8,6,14,0,101.0

### `Q-4:` Do these below operations:
- Find out the rank based on the "Team" column and save the result by adding a new column named "Rank".
- Change the datatype of this column to integer by using `np.int16`
- Set the index of the DataFrame by using this "Rank" column permanently.
- After that, sort the dataframe based on the "Rank" index.

In [21]:
df["Rank"] = df['Team'].rank(method='first')
df["Rank"] = df["Rank"].astype(np.int16)
df.set_index("Rank", inplace=True)
df.sort_index(inplace=True)
df.head()

,Team,Against,Group,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,Total Attempts,On Target,...,Yellow Cards,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored
Rank,,,,,,,,,,,,,,,,,,,,,
1,Argentina,Saudi Arabia,C,1,51,1,0,0,14,6,...,0,7,10,593,525,36,15,9,21,1
2,Argentina,Mexico,C,2,50,1,1,2,5,2,...,1,15,2,533,464,14,2,4,23,0
3,Argentina,Poland,C,2,67,1,1,2,25,13,...,1,11,0,862,814,22,5,9,5,0
4,Argentina,Australia,C,2,53,2,0,1,14,5,...,0,8,4,711,635,6,1,1,15,0
5,Argentina,Netherlands,C,2,44,2,0,1,15,6,...,8,18,2,603,511,16,4,8,30,5

## Questions on Titanic dataset.

[Titanic Dataset](https://www.kaggle.com/competitions/titanic).


- dataset 1: https://docs.google.com/spreadsheets/d/e/2PACX-1vQjh5HzZ1N0SU7ME9ZQRzeVTaXaGsV97rU8R7eAcg53k27GTstJp9cRUOfr55go1GRRvTz1NwvyOnuh/pub?gid=1562145139&single=true&output=csv
- dataset 2: https://docs.google.com/spreadsheets/d/e/2PACX-1vQcPvQsSC9aNFogvbUG08nu0bGHlOclGYaOlhND_LE5Ff7ZnHQ5VYzAgpyT5XNklgiT54SsNgHePsUa/pub?gid=1656109608&single=true&output=csv

### `Q-5:` Do the below tasks:
1. With dataset 1, drop those records which only have missing values of the "Age" column permanently.

2. With the dataset 2, fill the missing values with 20 to the only "Age" column permanently.

In [26]:
titanic_df1 = pd.read_csv("https://www.google.com/url?q=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2Fe%2F2PACX-1vQjh5HzZ1N0SU7ME9ZQRzeVTaXaGsV97rU8R7eAcg53k27GTstJp9cRUOfr55go1GRRvTz1NwvyOnuh%2Fpub%3Fgid%3D1562145139%26single%3Dtrue%26output%3Dcsv")
titanic_df2 = pd.read_csv("https://www.google.com/url?q=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2Fe%2F2PACX-1vQcPvQsSC9aNFogvbUG08nu0bGHlOclGYaOlhND_LE5Ff7ZnHQ5VYzAgpyT5XNklgiT54SsNgHePsUa%2Fpub%3Fgid%3D1656109608%26single%3Dtrue%26output%3Dcsv")

In [33]:
titanic_df1.dropna(subset=['Age'], inplace=True)
titanic_df2['Age'] = titanic_df2['Age'].fillna(20)

### `Q-6:` Make a dataframe of each team in IPL with details like - Team Name, Matches Played, Win%, Home Win%, Away Win%.
Show sorted dataframe on Win%

Replace old team name as new name before performing any tasks.
```
Delhi Daredevils ->Delhi Capitals
Kings XI Punjab -> Punjab Kings
Rising Pune Supergiants -> Rising Pune Supergiant
```

Note: Team1 represents Home team. Exclude not result matches.

In [34]:
# code here
ipl_matches = "https://docs.google.com/spreadsheets/d/e/2PACX-1vRy2DUdUbaKx_Co9F0FSnIlyS-8kp4aKv_I0-qzNeghiZHAI_hw94gKG22XTxNJHMFnFVKsO4xWOdIs/pub?gid=1655759976&single=true&output=csv"
matches = pd.read_csv(ipl_matches)
changed_name = {'Delhi Daredevils':'Delhi Capitals',
                'Kings XI Punjab':'Punjab Kings',
                'Rising Pune Supergiants':'Rising Pune Supergiant'}
matches.replace(changed_name.keys(), changed_name.values(), inplace=True)

In [35]:
df = matches[~matches.WinningTeam.isna()]
new_df = pd.DataFrame()
teams = df.Team1.unique()
data = []
for team in teams:
    played = df[(df.Team1 == team) | (df.Team2 == team)].shape[0]
    wins = df[df.WinningTeam == team].shape[0]
    home_win = df[(df.WinningTeam == team) & (df.Team1 == team)].shape[0] / df[df.Team1 == team].shape[0] * 100
    away_win = df[(df.WinningTeam == team) & (df.Team2 == team)].shape[0] / df[df.Team2 == team].shape[0] * 100
    data.append([team, played, wins/played*100, home_win, away_win])
new_df[["Team", "Matches Played", "Win Percentage", "Home Win Percentage", "Away Win Percentage"]] = data
new_df.sort_values("Win Percentage", inplace=True, ascending=False)
new_df

,Team,Matches Played,Win Percentage,Home Win Percentage,Away Win Percentage
5,Gujarat Titans,16,75.0,57.142857,88.888889
6,Lucknow Super Giants,15,60.0,87.5,28.571429
4,Chennai Super Kings,208,58.173077,58.558559,57.731959
9,Mumbai Indians,231,56.709957,58.035714,55.462185
7,Kolkata Knight Riders,223,51.121076,53.333333,49.152542
0,Rajasthan Royals,190,50.526316,55.05618,46.534653
10,Rising Pune Supergiant,30,50.0,50.0,50.0
2,Sunrisers Hyderabad,152,49.342105,52.173913,46.987952
1,Royal Challengers Bangalore,223,48.878924,49.593496,48.0
3,Delhi Capitals,222,46.396396,46.902655,45.87156
8,Punjab Kings,218,46.330275,45.454545,47.222222
11,Gujarat Lions,30,43.333333,31.25,57.142857
14,Kochi Tuskers Kerala,14,42.857143,42.857143,42.857143
13,Deccan Chargers,75,38.666667,33.333333,44.444444
12,Pune Warriors,45,26.666667,26.086957,27.272727

### `Q-7:` Venues with most "no result" matches.

In [36]:
# code here
matches[matches.WonBy == "NoResults"].Venue.value_counts().index[0]

'M Chinnaswamy Stadium'